//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itas109 {

public enum BaudRate {
  BaudRate110 = 110,
  BaudRate300 = 300,
  BaudRate600 = 600,
  BaudRate1200 = 1200,
  BaudRate2400 = 2400,
  BaudRate4800 = 4800,
  BaudRate9600 = 9600,
  BaudRate14400 = 14400,
  BaudRate19200 = 19200,
  BaudRate38400 = 38400,
  BaudRate56000 = 56000,
  BaudRate57600 = 57600,
  BaudRate115200 = 115200,
  BaudRate921600 = 921600
}

}
