//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itas109 {

public enum Parity {
  ParityNone = 0,
  ParityOdd = 1,
  ParityEven = 2,
  ParityMark = 3,
  ParitySpace = 4
}

}
