//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itas109 {

public class SerialPortInfoVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<SerialPortInfo>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SerialPortInfoVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SerialPortInfoVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SerialPortInfoVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SerialPortInfoVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cserialportCSharpPINVOKE.delete_SerialPortInfoVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SerialPortInfoVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SerialPortInfo element in c) {
      this.Add(element);
    }
  }

  public SerialPortInfoVector(global::System.Collections.Generic.IEnumerable<SerialPortInfo> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SerialPortInfo element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public SerialPortInfo this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(SerialPortInfo[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(SerialPortInfo[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, SerialPortInfo[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public SerialPortInfo[] ToArray() {
    SerialPortInfo[] array = new SerialPortInfo[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<SerialPortInfo> global::System.Collections.Generic.IEnumerable<SerialPortInfo>.GetEnumerator() {
    return new SerialPortInfoVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new SerialPortInfoVectorEnumerator(this);
  }

  public SerialPortInfoVectorEnumerator GetEnumerator() {
    return new SerialPortInfoVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class SerialPortInfoVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<SerialPortInfo>
  {
    private SerialPortInfoVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public SerialPortInfoVectorEnumerator(SerialPortInfoVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public SerialPortInfo Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (SerialPortInfo)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    cserialportCSharpPINVOKE.SerialPortInfoVector_Clear(swigCPtr);
  }

  public void Add(SerialPortInfo x) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_Add(swigCPtr, SerialPortInfo.getCPtr(x));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = cserialportCSharpPINVOKE.SerialPortInfoVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = cserialportCSharpPINVOKE.SerialPortInfoVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_reserve(swigCPtr, n);
  }

  public SerialPortInfoVector() : this(cserialportCSharpPINVOKE.new_SerialPortInfoVector__SWIG_0(), true) {
  }

  public SerialPortInfoVector(SerialPortInfoVector other) : this(cserialportCSharpPINVOKE.new_SerialPortInfoVector__SWIG_1(SerialPortInfoVector.getCPtr(other)), true) {
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public SerialPortInfoVector(int capacity) : this(cserialportCSharpPINVOKE.new_SerialPortInfoVector__SWIG_2(capacity), true) {
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private SerialPortInfo getitemcopy(int index) {
    SerialPortInfo ret = new SerialPortInfo(cserialportCSharpPINVOKE.SerialPortInfoVector_getitemcopy(swigCPtr, index), true);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private SerialPortInfo getitem(int index) {
    SerialPortInfo ret = new SerialPortInfo(cserialportCSharpPINVOKE.SerialPortInfoVector_getitem(swigCPtr, index), false);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, SerialPortInfo val) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_setitem(swigCPtr, index, SerialPortInfo.getCPtr(val));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(SerialPortInfoVector values) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_AddRange(swigCPtr, SerialPortInfoVector.getCPtr(values));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public SerialPortInfoVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = cserialportCSharpPINVOKE.SerialPortInfoVector_GetRange(swigCPtr, index, count);
    SerialPortInfoVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new SerialPortInfoVector(cPtr, true);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, SerialPortInfo x) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_Insert(swigCPtr, index, SerialPortInfo.getCPtr(x));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, SerialPortInfoVector values) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_InsertRange(swigCPtr, index, SerialPortInfoVector.getCPtr(values));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_RemoveAt(swigCPtr, index);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_RemoveRange(swigCPtr, index, count);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SerialPortInfoVector Repeat(SerialPortInfo value, int count) {
    global::System.IntPtr cPtr = cserialportCSharpPINVOKE.SerialPortInfoVector_Repeat(SerialPortInfo.getCPtr(value), count);
    SerialPortInfoVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new SerialPortInfoVector(cPtr, true);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    cserialportCSharpPINVOKE.SerialPortInfoVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, SerialPortInfoVector values) {
    cserialportCSharpPINVOKE.SerialPortInfoVector_SetRange(swigCPtr, index, SerialPortInfoVector.getCPtr(values));
    if (cserialportCSharpPINVOKE.SWIGPendingException.Pending) throw cserialportCSharpPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
