//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itas109 {

public enum SerialPortError {
  ErrorUnknown = -1,
  ErrorOK = 0,
  ErrorFail = 1,
  ErrorNotImplemented,
  ErrorInner,
  ErrorNullPointer,
  ErrorInvalidParam,
  ErrorAccessDenied,
  ErrorOutOfMemory,
  ErrorTimeout,
  ErrorNotInit,
  ErrorInitFailed,
  ErrorAlreadyExist,
  ErrorNotExist,
  ErrorAlreadyOpen,
  ErrorNotOpen,
  ErrorOpenFailed,
  ErrorCloseFailed,
  ErrorWriteFailed,
  ErrorReadFailed
}

}
